BACKUP_ROOT=~/.local/share/mylinuxconfig/backups
NVIM_REPO_URL=https://github.com/Fenix-llf/MyAstroNVIMConfig.git
# 这里也可以定义只在本次部署过程中使用的临时环境变量。
# 这些变量会传给 `.sh` manifest，但不会自动写入你的 shell 配置。
#
# 示例：
# SOME_TEMP_VAR=some-value
